# Generated by Django 5.0.1 on 2024-09-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.CountIngredientInRecipe', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
