# Generated by Django 3.2.3 on 2024-10-05 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['-id'], 'verbose_name': 'Количество ингредиентов в рецепте', 'verbose_name_plural': 'Количество ингредиентов в рецепте'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не менее 1 минуты!'), django.core.validators.MaxValueValidator(1000, message='Время приготовления не более 1000 минут!')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не менее 1 минуты!'), django.core.validators.MaxValueValidator(1000, message='Время приготовления не более 1000 минут!')], verbose_name='Количество'),
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
